name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Node dependencies
        run: npm ci
      - name: Package VSIX
        run: npm run package
      - name: Archive VSIX
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: vsix
          path: '*.vsix'
      - name: Test
        run: npm run test:prep && npm run test -- --coverage
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format

  test-vscode:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-installer: [actions, conda]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'powershell' || 'bash -el {0}' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: proj
      - name: Get node path
        run: which node
      - name: Get npm path
        run: which npm
      - name: Get node version
        run: node --version
      - name: Install Node.js via setup-node
        if: matrix.node-installer == 'actions'
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version-file: 'proj/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'proj/**/package-lock.json'
      - name: Setup miniconda
        if: matrix.node-installer == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate: true
          activate-environment: ""
      - name: Install Node via conda
        if: matrix.node-installer == 'conda'
        run: conda install -y --quiet -c conda-forge "nodejs>=22"
      - run: conda info
        if: matrix.node-installer == 'conda'
      - run: conda list
        if: matrix.node-installer == 'conda'
      - run: conda config --show
        if: matrix.node-installer == 'conda'
      - name: Get node path
        run: which node
      - name: Get npm path
        run: which npm
      - name: Get node version
        run: node --version
      - name: Install Node dependencies
        run: npm ci
        working-directory: proj
      - name: Build
        run: npm run build
        working-directory: proj
      - name: Copy test projects
        run: cp -r proj/test/projects test-projects
      - name: Install test project dependencies
        run: npm ci
        working-directory: test-projects/conventional
      - name: Run VSCode tests without global install
        if: runner.os != 'Linux'
        run: npm run test:vscode
        working-directory: proj
        env:
          CLTEST_PROJECTS_ROOT: ../test-projects
      - name: Run VSCode tests without global install (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm run test:vscode
        working-directory: proj
        env:
          CLTEST_PROJECTS_ROOT: ../test-projects
      - name: Install global commitlint/conventional commits
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Run VSCode tests with global install
        if: runner.os != 'Linux'
        run: npm run test:vscode
        working-directory: proj
        env:
          CLTEST_PROJECTS_ROOT: ../test-projects
          CLTEST_GLOBAL: true
      - name: Run VSCode tests with global install (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm run test:vscode
        working-directory: proj
        env:
          CLTEST_PROJECTS_ROOT: ../test-projects
          CLTEST_GLOBAL: true
