name: Version and Tag

on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: ${{ secrets.GIT_PUSH_TOKEN }}
          fetch-depth: 0
      - name: Configure committer
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            test/project/package-lock.json
      - name: Install Node dependencies
        run: npm ci
      - name: Bump version
        run: npm run release
      - name: Push changes
        run: |
          git push --follow-tags
